/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BattingLogs {
  all_walks: number | null;
  at_bat: number | null;
  bat_team: string | null;
  batter: number | null;
  double: number | null;
  estimated_ba_using_speedangle: number | null;
  estimated_slg_using_speedangle: number | null;
  estimated_woba_using_speedangle: number | null;
  game_date: Timestamp | null;
  game_pk: number | null;
  game_year: number | null;
  hit: number | null;
  hit_by_pitch: number | null;
  home_run: number | null;
  intent_walk: number | null;
  p_throws: string | null;
  pitch_team: string | null;
  plate_appearance: number | null;
  sac_fly: number | null;
  single: number | null;
  stand: string | null;
  triple: number | null;
  walk: number | null;
}

export interface DuckdbExtensions {
  autoload: Generated<boolean>;
  name: string;
  repository: Generated<string>;
}

export interface DuckdbTables {
  default_database: string;
  duckdb_db: string;
  motherduck_catalog_version: string | null;
  relid: string;
}

export interface PlayerIsQualified {
  batter: number | null;
  min_pa: Numeric | null;
  pa: Int8 | null;
  qualified: boolean | null;
}

export interface PlayerQualifiers {
  batter: number | null;
  min_pa: Numeric | null;
}

export interface Players {
  bat_side: string | null;
  birth_date: Timestamp | null;
  current_age: number | null;
  current_team_id: number | null;
  first_name: string | null;
  full_name: string | null;
  id: number | null;
  last_name: string | null;
  pitch_hand: string | null;
  position_code: string | null;
  position_name: string | null;
  primary_number: number | null;
  use_name: string | null;
}

export interface Statcast {
  age_bat: number | null;
  age_bat_legacy: number | null;
  age_pit: number | null;
  age_pit_legacy: number | null;
  api_break_x_arm: number | null;
  api_break_x_batter_in: number | null;
  api_break_z_with_gravity: number | null;
  arm_angle: string | null;
  at_bat_number: number | null;
  attack_angle: number | null;
  attack_direction: number | null;
  away_score: number | null;
  away_team: string | null;
  ax: number | null;
  ay: number | null;
  az: number | null;
  babip_value: number | null;
  balls: number | null;
  bat_score: number | null;
  bat_score_diff: number | null;
  bat_speed: number | null;
  bat_win_exp: number | null;
  batter: number | null;
  batter_days_since_prev_game: string | null;
  batter_days_until_next_game: string | null;
  bb_type: string | null;
  delta_home_win_exp: number | null;
  delta_pitcher_run_exp: number | null;
  delta_run_exp: number | null;
  des: string | null;
  description: string | null;
  effective_speed: number | null;
  estimated_ba_using_speedangle: number | null;
  estimated_slg_using_speedangle: number | null;
  estimated_woba_using_speedangle: number | null;
  events: string | null;
  fielder_2: number | null;
  fielder_3: number | null;
  fielder_4: number | null;
  fielder_5: number | null;
  fielder_6: number | null;
  fielder_7: number | null;
  fielder_8: number | null;
  fielder_9: number | null;
  fld_score: number | null;
  game_date: Timestamp | null;
  game_pk: number | null;
  game_type: string | null;
  game_year: number | null;
  hc_x: number | null;
  hc_y: number | null;
  hit_distance_sc: number | null;
  hit_location: number | null;
  home_score: number | null;
  home_score_diff: number | null;
  home_team: string | null;
  home_win_exp: number | null;
  hyper_speed: number | null;
  if_fielding_alignment: string | null;
  inning: number | null;
  inning_topbot: string | null;
  intercept_ball_minus_batter_pos_x_inches: number | null;
  intercept_ball_minus_batter_pos_y_inches: number | null;
  iso_value: number | null;
  launch_angle: number | null;
  launch_speed: number | null;
  launch_speed_angle: number | null;
  n_priorpa_thisgame_player_at_bat: number | null;
  n_thruorder_pitcher: number | null;
  of_fielding_alignment: string | null;
  on_1b: string | null;
  on_2b: number | null;
  on_3b: number | null;
  outs_when_up: number | null;
  p_throws: string | null;
  pfx_x: number | null;
  pfx_z: number | null;
  pitch_name: string | null;
  pitch_number: number | null;
  pitch_type: string | null;
  pitcher: number | null;
  pitcher_days_since_prev_game: string | null;
  pitcher_days_until_next_game: string | null;
  plate_x: number | null;
  plate_z: number | null;
  player_name: string | null;
  post_away_score: number | null;
  post_bat_score: number | null;
  post_fld_score: number | null;
  post_home_score: number | null;
  release_extension: number | null;
  release_pos_x: number | null;
  release_pos_y: number | null;
  release_pos_z: number | null;
  release_speed: number | null;
  release_spin_rate: number | null;
  spin_axis: number | null;
  stand: string | null;
  strikes: number | null;
  swing_length: number | null;
  swing_path_tilt: number | null;
  sz_bot: number | null;
  sz_top: number | null;
  type: string | null;
  vx0: number | null;
  vy0: number | null;
  vz0: number | null;
  woba_denom: number | null;
  woba_value: number | null;
  zone: number | null;
}

export interface TeamQualifiers {
  games: Int8 | null;
  min_pa: Numeric | null;
  team: string | null;
}

export interface Teams {
  abbreviation: string | null;
  division: string | null;
  id: number | null;
  league: string | null;
  name: string | null;
}

export interface Weights {
  c_fip: number | null;
  game_year: number | null;
  league_woba: number | null;
  r_w_ratio: number | null;
  run_cs: number | null;
  run_sb: number | null;
  runs_per_pa: number | null;
  w_bb: number | null;
  w_double: number | null;
  w_hbp: number | null;
  w_home_run: number | null;
  w_single: number | null;
  w_triple: number | null;
  woba_scale: number | null;
}

export interface DB {
  batting_logs: BattingLogs;
  "duckdb.extensions": DuckdbExtensions;
  "duckdb.tables": DuckdbTables;
  player_is_qualified: PlayerIsQualified;
  player_qualifiers: PlayerQualifiers;
  players: Players;
  statcast: Statcast;
  team_qualifiers: TeamQualifiers;
  teams: Teams;
  weights: Weights;
}
